version: '2'
services:
  drupal:
    image: drupal
    ports:
      - 8081:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/properties
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:11.6
    environment:
    - POSTGRES_PASSWORD=password

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites: 
  drupal-themes: