apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-hostnetwork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-hostnetwork
  template:
    metadata:
      labels:
        app: httpd-hostnetwork
    spec:
      hostNetwork: true
      containers:
        - name: httpd
          image: httpd
