apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeone-1
  template:
    metadata:
      labels:
        app: nodeone-1
    spec:
      containers:
        - name: nodeone-1
          image: irarelycode/nodeone

---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-srv
spec:
  type: NodePort
  selector:
    name: nodeone-1
  ports:
    - port: 5342
      targetPort: 5342
      protocol: TCP
